/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login with email + password; success sets the `skb_session` JWT cookie
     *     (HttpOnly, SameSite=Lax, Path=/) valid for 24 hours.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a user (Argon2id hash; duplicate email → 409). */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/blog/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Published blog posts, newest first. Public — no auth. */
    get: operations["list_posts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/blog/posts/{document_id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Publish the blog post for a document (author JWT required; readers and
     *     unauthenticated callers get 401, an unconfigured secret 503).
     */
    post: operations["publish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chat/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Streaming chat over the knowledge base. The response is
     *     `text/event-stream`: `citation` (all search hits) → `token`×N → `done`,
     *     or `error` (in-band, terminal) with HTTP 200 throughout.
     */
    post: operations["chat_stream"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List document summaries with optional limit/offset/order and the
     *     `<created_at>,<id>` keyset cursor.
     */
    get: operations["list_documents"];
    put?: never;
    /**
     * Ingest a new document. The request body is a transparent
     *     [`UploadRequest`] passthrough; exactly one of `path`/`url`/`content`/
     *     `content_base64` must be set (enforced by core).
     * @description Uploads marked `metadata.app == "blog"` require an author JWT (401 for
     *     missing/invalid tokens or reader role, 503 when the JWT secret is
     *     unconfigured) and auto-create the `blog_post` registry row; other
     *     uploads are unchanged and need no auth.
     */
    post: operations["create_document"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch one document's detail; `?include_chunks=true` adds the chunks. */
    get: operations["get_document"];
    /**
     * Replace a document's content. Core has no update API, so this is a
     *     composite: fetch the old document (404 when absent), run ONE upload with
     *     `force` stripped, then branch on the response:
     * @description - new id (`content` changed): delete the old document, return the new id —
     *       clients re-point stored references at it.
     *     - `skipped` (identical sha256 already ingested): keep the old document and
     *       return its id — deleting here would destroy the only copy.
     *
     *     `force` is never honored on PUT: `force=true` upserts in place (keeping
     *     the id), and the subsequent old-id delete would destroy the just-updated
     *     document.
     */
    put: operations["update_document"];
    post?: never;
    /**
     * Delete a document and its chunks. Responds 204 with no body. The
     *     `blog_post` registry row (if any) is dropped first so the published-post
     *     listing never references a deleted document; the targeted delete is a
     *     no-op for documents without a post.
     */
    delete: operations["delete_document"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/{id}/backlinks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Documents whose chunks mention any entity this document's chunks mention
     *     (reverse `mentions` walk). A document with no extracted entities has no
     *     backlinks (200, empty list); a missing id is 404 E_DOCUMENT_NOT_FOUND.
     */
    get: operations["document_backlinks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/graph/query": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Traverse entity relations from an entity name or record id. Validation
     *     (depth 1-5, limit bounds, empty `from`) is core-owned: out-of-range depth
     *     surfaces as 400 E_VALIDATION, a missing start document as 404.
     */
    post: operations["graph_query"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe. Never touches the database. */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Hybrid/vector/keyword search. The body is a transparent passthrough:
     *     mode/top_k defaults and every range check are core-owned
     *     (`KnowledgeBase::search` fills them from `config.search`).
     */
    post: operations["search"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search/expand": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Expand search hits along the knowledge graph (spec §6): each hit's chunk
     *     mentions entities, `related_to` edges extend the frontier for
     *     `max_expand - 1` further hops, and chunks mentioning any frontier entity
     *     come back with a hop-decayed score. Bounded by core (frontier caps, hop
     *     decay); no server-side validation is added.
     */
    post: operations["expand_search"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Body of successful register/login responses. */
    AuthResponse: {
      email: string;
      role: string;
    };
    /** @description One backlinking document. */
    BacklinkDocument: {
      id: string;
      title: string;
    };
    /** @description Body of the `GET /api/documents/{id}/backlinks` response. */
    BacklinksResponse: {
      documents: components["schemas"]["BacklinkDocument"][];
    };
    /** @description Item of the `GET /api/blog/posts` response array. */
    BlogPostSummary: {
      /** @description Author email. */
      author: string;
      created_at: string;
      /** @description Full document record id (`document:<key>`). */
      document_id: string;
      /** @description Title from the underlying document record. */
      title: string;
    };
    /**
     * @description Body of `POST /api/chat/stream`. SPECIFICATION.md has no SSE request
     *     section yet (todo 9 adds it), so the shape is `{"message": string}`.
     */
    ChatStreamRequest: {
      message: string;
    };
    /** @description Chunk of a document detail response (`include_chunks=true`). */
    ChunkInfoResponse: {
      content: string;
      heading?: string | null;
      idx: number;
      token_count: number;
    };
    /** @description Body of the `GET /api/documents/{id}` response. */
    DocumentDetailResponse: {
      chunks?: components["schemas"]["ChunkInfoResponse"][] | null;
      content: string;
      created_at: string;
      id: string;
      sha256: string;
      source: string;
      source_type: string;
      title: string;
    };
    /** @description Item of the `GET /api/documents` response array. */
    DocumentSummaryResponse: {
      chunk_count: number;
      created_at: string;
      id: string;
      sha256: string;
      source: string;
      title: string;
    };
    /** @description Error body shape returned by every failing endpoint (`{"code","message"}`). */
    ErrorResponse: {
      /** @description Machine-readable code, e.g. `E_VALIDATION`. */
      code: string;
      message: string;
    };
    /**
     * @description Body of `POST /api/search/expand`: search hits plus the expansion hop
     *     depth consumed by core's `expand_search_hits`.
     */
    ExpandRequest: {
      hits: components["schemas"]["SearchHit"][];
      max_expand: number;
    };
    /**
     * @description Body of the `POST /api/search/expand` response. `entity_origins` maps the
     *     `"<document_id>/<chunk_idx>"` key of each ORIGINAL hit to the entities its
     *     chunk mentions.
     */
    ExpandResponse: {
      entity_origins: {
        [key: string]: string[];
      };
      hits: components["schemas"]["SearchHit"][];
    };
    /** @description Edge of the `POST /api/graph/query` result graph. */
    GraphEdge: {
      from: string;
      relation: string;
      to: string;
    };
    /** @description Node of the `POST /api/graph/query` result graph. */
    GraphNode: {
      depth: number;
      id: string;
      kind: string;
      name: string;
    };
    /**
     * @description Body of `POST /api/graph/query`: a transparent passthrough. `from` is an
     *     entity name or a full record id (`entity:<key>` / `document:<key>`);
     *     `depth` (1-5) and `limit` bounds are core-validated.
     */
    GraphQueryRequest: {
      /** @description Hop depth 1-5 (core-validated; out-of-range → 400 E_VALIDATION). */
      depth?: number | null;
      from: string;
      limit?: number | null;
      relation?: string | null;
    };
    /** @description Body of the `POST /api/graph/query` response. */
    GraphQueryResult: {
      edges: components["schemas"]["GraphEdge"][];
      nodes: components["schemas"]["GraphNode"][];
    };
    HealthResponse: {
      status: string;
    };
    /** @description Body of `POST /api/auth/login`. */
    LoginRequest: {
      email: string;
      password: string;
    };
    /** @description Body of the successful publish response. */
    PublishResponse: {
      document_id: string;
      published: boolean;
    };
    /** @description Body of `POST /api/auth/register`. */
    RegisterRequest: {
      email: string;
      password: string;
      /** @description `reader` (default) or `author`. */
      role?: string | null;
    };
    /** @description One search result. */
    SearchHit: {
      chunk_idx: number;
      content: string;
      document_id: string;
      /** @description Query terms found in the chunk (keyword / hybrid keyword leg). */
      highlights?: string[] | null;
      /** @description Entities that led to this hit via graph expansion. */
      matched_entities?: string[] | null;
      /** Format: double */
      score: number;
      source?: string | null;
      title?: string | null;
    };
    /**
     * @description Body of `POST /api/search`: a transparent search passthrough. An omitted
     *     `mode`/`top_k` is filled by `KnowledgeBase::search` from the core config
     *     (`config.search.default_mode` / `config.search.top_k`).
     */
    SearchRequest: {
      /** @description Document-field post-filter (title/source/source_type/mime/sha256). */
      filter?: {
        [key: string]: string;
      } | null;
      /** @description Graph-expansion hop depth (0-5, core-validated); omitted → none. */
      graph_expand?: number | null;
      /** @description `hybrid` | `vector` | `keyword`; omitted → core config default. */
      mode?: string | null;
      query: string;
      top_k?: number | null;
    };
    /** @description Body of the `POST /api/search` response. */
    SearchResponse: {
      /** Format: int64 */
      elapsed_ms: number;
      hits: components["schemas"]["SearchHit"][];
      /** @description Mode actually used (the configured default when the request omitted it). */
      mode: string;
    };
    /**
     * @description Body of the `PUT /api/documents/{id}` response. The client must re-point
     *     stored references at `document_id` (it differs from the PUT target id when
     *     the content changed).
     */
    UpdateDocumentResponse: {
      document_id: string;
    };
    /**
     * @description Body of `POST /api/documents` and `PUT /api/documents/{id}`: a transparent
     *     [`UploadRequest`] passthrough.
     */
    UploadDocumentRequest: {
      /** @description Inline UTF-8 content. */
      content?: string | null;
      /** @description Inline base64-encoded binary content. */
      content_base64?: string | null;
      /** @description Only honored on POST; the PUT handler strips it (see its handler docs). */
      force?: boolean | null;
      metadata?: {
        [key: string]: string;
      } | null;
      /** @description File path to upload (server-side read). */
      path?: string | null;
      tags?: string[] | null;
      title?: string | null;
      /** @description URL to fetch and ingest. */
      url?: string | null;
    };
    /** @description Body of the successful `POST /api/documents` response. */
    UploadDocumentResponse: {
      chunks: number;
      /** @description `None` when the upload was skipped (identical sha256 already ingested). */
      document_id?: string | null;
      entities: string[];
      sha256: string;
      /** @description `created` | `updated` | `skipped` | `empty`. */
      status: string;
      title: string;
      tokens: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Session cookie set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description JWT secret not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description User registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid registration */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_posts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published blog posts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogPostSummary"][];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  publish_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Document record id (`document:<key>`) */
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Post published */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublishResponse"];
        };
      };
      /** @description Missing/invalid token or non-author role */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description No blog post for the document */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description JWT secret not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  chat_stream: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatStreamRequest"];
      };
    };
    responses: {
      /** @description SSE stream: citation → token* → done; pipeline failures are terminal in-band error events (HTTP status stays 200) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
    };
  };
  list_documents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        limit: number | null;
        offset: number | null;
        /** @description `created_desc` | `created_asc` | `title_asc` | `title_desc`. */
        order: string | null;
        /** @description Keyset cursor `<created_at>,<id>` as returned by the previous page. */
        after: string | null;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document summaries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentSummaryResponse"][];
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_document: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadDocumentRequest"];
      };
    };
    responses: {
      /** @description Document ingested */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadDocumentResponse"];
        };
      };
      /** @description Invalid upload request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Blog upload without an author session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unsupported source format */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description JWT secret not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_document: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Document record id (`document:<key>`) */
        id: string;
        /** @description Include the document's chunks in the response. */
        include_chunks: boolean | null;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentDetailResponse"];
        };
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_document: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Document record id (`document:<key>`) */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadDocumentRequest"];
      };
    };
    responses: {
      /** @description Current document id after the update */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateDocumentResponse"];
        };
      };
      /** @description Invalid upload request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unsupported source format */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_document: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Document record id (`document:<key>`) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  document_backlinks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Document record id (`document:<key>`) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backlinking documents */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BacklinksResponse"];
        };
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  graph_query: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GraphQueryRequest"];
      };
    };
    responses: {
      /** @description Graph nodes and edges */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GraphQueryResult"];
        };
      };
      /** @description Invalid graph query */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Start document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  search: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Ranked search hits */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Invalid search request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  expand_search: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExpandRequest"];
      };
    };
    responses: {
      /** @description Expanded hits plus per-hit origin entities */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExpandResponse"];
        };
      };
      /** @description Server fault */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
